<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Bugs.aspx.cs" Inherits="Helpdesk.Bugs" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <br /><br />
            <asp:Label ID="lblBug" runat="server" Text="Bug:"></asp:Label>&nbsp;&nbsp;&nbsp;&nbsp;<asp:TextBox ID="txtBug" runat="server"></asp:TextBox>
            <br /><br />
            <asp:Label ID="lblUser" runat="server" Text="User:"></asp:Label>&nbsp;&nbsp;&nbsp;&nbsp;<asp:TextBox ID="txtUser" runat="server"></asp:TextBox>
            <br />
            <br />
            <br />&nbsp;<asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" DataKeyNames="Id" DataSourceID="BugDataSource2">
                <Columns>
                    <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
                    <asp:BoundField DataField="AssignedByUserId" HeaderText="AssignedByUserId" SortExpression="AssignedByUserId" />
                    <asp:BoundField DataField="AssignedToUserId" HeaderText="AssignedToUserId" SortExpression="AssignedToUserId" />
                    <asp:BoundField DataField="Summary" HeaderText="Summary" SortExpression="Summary" />
                    <asp:BoundField DataField="Description" HeaderText="Description" SortExpression="Description" />
                    <asp:BoundField DataField="Priority" HeaderText="Priority" SortExpression="Priority" />
                    <asp:BoundField DataField="Status" HeaderText="Status" SortExpression="Status" />
                    <asp:BoundField DataField="Date" HeaderText="Date" SortExpression="Date" />
                </Columns>
                <SelectedRowStyle BackColor="#00CC99" />
            </asp:GridView>
            <asp:SqlDataSource ID="BugDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:BugConnectionString %>" DeleteCommand="DELETE FROM [Bugs] WHERE [Id] = @Id" InsertCommand="INSERT INTO [Bugs] ([AssignedByUserId], [AssignedToUserId], [Summary], [Description], [Priority], [Status], [Date]) VALUES (@AssignedByUserId, @AssignedToUserId, @Summary, @Description, @Priority, @Status, @Date)" SelectCommand="SELECT * FROM [Bugs]" UpdateCommand="UPDATE [Bugs] SET [AssignedByUserId] = @AssignedByUserId, [AssignedToUserId] = @AssignedToUserId, [Summary] = @Summary, [Description] = @Description, [Priority] = @Priority, [Status] = @Status, [Date] = @Date WHERE [Id] = @Id">
                <DeleteParameters>
                    <asp:Parameter Name="Id" Type="Int32" />
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="AssignedByUserId" Type="Int32" />
                    <asp:Parameter Name="AssignedToUserId" Type="Int32" />
                    <asp:Parameter Name="Summary" Type="String" />
                    <asp:Parameter Name="Description" Type="String" />
                    <asp:Parameter Name="Priority" Type="String" />
                    <asp:Parameter Name="Status" Type="String" />
                    <asp:Parameter DbType="Date" Name="Date" />
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="AssignedByUserId" Type="Int32" />
                    <asp:Parameter Name="AssignedToUserId" Type="Int32" />
                    <asp:Parameter Name="Summary" Type="String" />
                    <asp:Parameter Name="Description" Type="String" />
                    <asp:Parameter Name="Priority" Type="String" />
                    <asp:Parameter Name="Status" Type="String" />
                    <asp:Parameter DbType="Date" Name="Date" />
                    <asp:Parameter Name="Id" Type="Int32" />
                </UpdateParameters>
            </asp:SqlDataSource>
            &nbsp;
        </div>
    </form>
</body>
</html>
